# Site settings
title:          Yoga+UX Blog
description:    "Exploring and challenging UX processes, mindsets, significance of empathy, approaches to collaboration, and other dandy things." 
url:            "https://itscrystal.github.io/blog"

# Author
author:
  name:         Crystal Tong
  url:          https://crystaltong.co
  email:        hello@crystaltong.co

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
